### ISSUE TITLE
Ubuntuで、npm install onigurumaする際にエラーが出る

### ISSUE THREAD

**Issue by geckotang** [watilde/npm#10]
- 背景
  - Ubuntu上で、`npm install oniguruma`をした際にエラーになりインストールが出来ない
- 実行環境
  - Node.jsのバージョン
    - v4.2.2
  - npmのバージョン
    - 2.14.7
  - OSのバージョン
    - `Linux www7282uf 2.6.32-40-server #87-Ubuntu SMP Tue Mar 6 02:10:02 UTC 2012 x86_64 GNU/Linux`
- エラーログ
  - https://gist.github.com/geckotang/5e3fcdff9aed1322b90faed696e2ac0f

**Comment by watilde** [comment]
こんにちは！
`node-gyp` の `rebuild`でコケてるみたいですね。下記の2点を確認お願いします。
1. globalにinstallされている `gyp` を消す
   参考: https://github.com/nodejs/node-gyp/issues/363#issuecomment-32234646
2. Node.js v4でNaNに変更があったので、gccを4.8以上にする
   参考: https://github.com/nodejs/nan/issues/448

**Comment by geckotang** [comment]
> globalにinstallされている gyp を消す

```
$ apt-get remove gyp
E: ロックファイル /var/lib/dpkg/lock をオープンできません - open (13: 許可がありません)
E: 管理用ディレクトリ (/var/lib/dpkg/) をロックできません。root 権限で実行していますか?

$ python -c 'import gyp; print gyp.__file__'
Traceback (most recent call last):
 File "<string>", line 1, in <module>
ImportError: No module named gyp
```

> Node.js v4でNaNに変更があったので、gccを4.8以上にする

http://qiita.com/aKenjiKato/items/e9011e02feb131c4526e を参考にして
g++とgccをv4.4からv4.8にしたら、 `npm i oniguruma` することができました。
ありがとうござます。
