### ISSUE TITLE
private scoped modulesを削除するには

### ISSUE THREAD

**Issue by 59naga** [watilde/npm#13]
Goedenavond, iedereen.
`npm publish`で`--acess=public`し忘れた[scoped modules](https://docs.npmjs.com/misc/scope)は削除不能になります。
例えば、`@59naga/array-from`はログイン時に[以下のように表示されており](https://www.npmjs.com/~59naga)、これを`npm unpublish @59naga/array-from --force`としても削除できません。
![2016-05-07 3 16 06](https://cloud.githubusercontent.com/assets/1548478/15082326/1cc4da46-1402-11e6-977a-5b75a7110972.gif)

**Comment by watilde** [comment]
報告ありがとうございます！手元でも再現しました。version上げても `publish --acess=public` できなくて詰みますねこれ。
issue報告とpatch作成したいと思いますm(_ _)m

**Comment by 59naga** [comment]
よろしくお願いします＼\٩( 'ω' )و //／
ちなみに、クレカ登録後なら削除できるかなーっと思って登録してみたんですが、支払った後でも消せないみたいですね。(☍﹏⁰)｡

**Comment by watilde** [comment]
報告しておきました！ https://github.com/npm/registry/issues/15

registryのscoped package周りの実装は、
セキュリティ上の理由か何かで非公開みたいなので、これにて様子見とします 💦

**Comment by terrierscript** [comment]
私も以前`--access=public`し忘れて操作できなくなった事があり、その際サポートに問い合わせた所、下記のコマンドを使ってpublicにできることを教えて頂きました。

```
$ npm access public @scope/package
```

削除については試してませんが、ご参考になれば。
- https://docs.npmjs.com/cli/access
- https://docs.npmjs.com/getting-started/scoped-packages

**Comment by 59naga** [comment]
試しに`@59naga/hoge`をprivate modulesとしてpublishして、その後`npm access public @59naga/hoge`とすることで、`npm unpublish @59naga/hoge --force`で削除できることを確認しました。

また、自分もnpmjsに問い合わせてみたところ、「２４時間経過したものは削除できない」という回答を頂いたので、その場合は直接削除してもらうしか無いようです。

```
May 9, 02:59
Hello.

Attempted to delete the mistake module registered "@59naga/array-from”, fail.
I have registered a credit card to solve this problem, but the result was the same.

Sorry to trouble you, can remove credit card information and module of above?
(Refund of the monthly fee paid today isn’t required. Please stop the straight-line payment).

—
by 59naga <i59naga@iclud.com>
https://www.npmjs.com/~59naga
```

```
May 9, 13:56

Hi there,

Thanks for reaching out. Right now, it is not possible to unpublish all modules that are more than 24 hours old, due to our new unpublish policy: http://blog.npmjs.org/post/141905368000/changes-to-npms-unpublish-policy
We are working on restoring the unpublish capability for private modules only.

I've gone ahead and unpublished @59naga/array-from It looks like you've already cancelled your subscription, and you will not receive any future bills.

Let me know if you have other questions.

Kiera
```

ひとまず、このissueは解決済みとさせて頂きます。ありがとうございました！
