### ISSUE TITLE
海外からもREADME.ja.mdが優先して表示される

### ISSUE THREAD

**Issue by kjirou** [watilde/npm#16]
## 質問と問題
package.json と同じディレクトリに README.md と README.ja.md を配置した npm パッケージを publish したところ、README.ja.md の方が npm レジストリホストに表示されてしまいました。

環境の問題かなと、以下を調整して再度遷移しましたが、変わりませんでした。

- `Accept-Language` が英語優先になるように、ブラウザの言語設定を変更
- npm アカウントをログアウト
- Chrome シークレットモードに切り替え

というところで、日本語用 README を置きたい場合に、本来的な対応としてどうすべきか、もしくは本来的ではなくてもいいので対応案、を教えて頂いても良いでしょうか！

（書いてから気付いたんですが、現在 README.ja.md が表示されているのは何かの偶然で、別に README が多言語対応されてる訳じゃないので、削って publish すればいいだけかも？）

## 実行環境等
npm publish した環境:
```
%node -v
v6.8.0
%npm -v
3.10.8
```

その npm パッケージ: https://www.npmjs.com/package/downspout

**Comment by watilde** [comment]
これはサイト側の正規表現を修正した方が良さそうですね。多言語対応と合わせて提案して、可能そうだったら修正もしてみます。ご連絡ありがとうございます 😃

**Comment by kjirou** [comment]
了解です。ありがとうございますー。
