### ISSUE TITLE
日本語でのIssueの報告について

### ISSUE THREAD

**Issue by watilde** [watilde/npm#2]
実験的に日本語でのissue報告を受け入れてみます。
できるだけ解決できるようにがんばります。

英語でissueを書くのが大変な複雑なバグの報告から、issueを上げるまでもない質問など、
npmに関連しているものでしたら何でもお気軽にissueを建ててみてください。

これからやること：
- [x] 報告についてのガイドラインを整備
- [x] default branchを差し替えて、READMEに説明を追加

**Comment by lacolaco** [comment]
:+1: 
応援します！

**Comment by watilde** [comment]
ありがとうございます！ToDoが終わったので、こちらのissueは閉じます😊
