### ISSUE TITLE
日ごとの人気パッケージを知りたい

### ISSUE THREAD

**Issue by 59naga** [watilde/npm#4]
どうも、こんばんは。
新しく人気が出てきたパッケージを、日毎で確認できるようにしたいです。

現状、[npm/download-counts](https://github.com/npm/download-counts)を利用して、パッケージごとのダウンロード数を総当りで取得することが可能です。
ですがこの場合、著名な作者から芋づる式に取得するしか、方法が無いように見えます。
新しいorganizationや、ユーザーがpublishしたパッケージを見失うことがありそうです。

[github.com/trending](https://github.com/trending?l=javascript)のように、npmから、これらの情報を公開している場所を、提供していただくことは可能でしょうか？

**Comment by azu** [comment]
GitHubのトレンドページみたいなものは確かにない気がしますね。
- [npm-stat: download statistics for NPM packages](http://npm-stat.com/): ダウンロード数の推移
- [npm addict](https://npmaddict.com/): 新着

via [awesome-npm](https://github.com/sindresorhus/awesome-npm#web)

**Comment by watilde** [comment]
こんにちは！こちらに関してですが、私が知ってるのは下記の2つの方法です。

> 新しく人気が出てきたパッケージを、日毎で確認できるようにしたいです。

---

日毎の更新が得られるjson file
- https://registry.npmjs.org/-/all/static/today.json
- https://registry.npmjs.org/-/all/static/yesterday.json
- PSTの0時で更新されていると思います

Replicateする
- https://github.com/npm/npm-registry-couchapp/tree/master#replicating-the-registry
- skimdbを直叩きしている例
  - https://github.com/bcoe/npm-tweets/blob/master/lib/check-npm.js
  - `host` を `registry.npmjs.org` とするのがポイントなようです

**Comment by 59naga** [comment]
http://npm-today.berabou.me/

`Accept-Encoding:gzip`ヘッダによって`https://api.npmjs.org/downloads/point/last-day/`の結果が変わってしまうようです。

``` bash
curl https://api.npmjs.org/downloads/point/2016-03-07
# {"downloads":146607111,"start":"2016-03-07","end":"2016-03-07"}

curl https://api.npmjs.org/downloads/point/2016-03-07 -H "Accept-Encoding:gzip" | gunzip -
# {"downloads":null,"start":"2016-03-07","end":"2016-03-07"}
```

とりあえず上記のAPIを利用時にはgzipヘッダ無しで、逆に`npm/download-counts`はgzipヘッダありで運用してみようと思います。

**Comment by 59naga** [comment]
skimdbの場合、`startkey`,`endkey`を任意のDate.getTime()にすることで[過去を遡ってデータを取れるようです](http://npm-today.berabou.me/#/2015-01-01?_k=gxco5v)ね。
求めていた結果が得られましたので、issueを閉じます。情報ありがとうございました。
