### ISSUE TITLE
パッケージ利用者のNode.jsバージョンの統計を知りたい

### ISSUE THREAD

**Issue by teppeis** [watilde/npm#5]
npmパッケージの作者として、自分のパッケージを使っているユーザーがNode.js/io.jsのどのバージョンなのか統計を見たいです。
v0.10/v0.12のサポートを切って良いのか判断するための材料がほしいです。
特に最近はES6系の機能があるので、Babelを使うべきか使わないで良いかとかもあるので。

また、npmユーザー全体の統計を見れると現在のおよその全Node.jsユーザーのバージョン分布も見れるかも知れませんね。

**Comment by watilde** [comment]
より詳細な利用者の情報収集に関しては、公式見解として予定はあるみたいなんですが2年も前よりissueが作られて以来まだ実施に至っていないので、あまり期待ができないところかと思います。https://github.com/npm/npm/issues/6904

これはアイデアですが、
lifecycle scriptの`postinstall` をフックして情報をGoogle Analyticsに送るjsを書くのはいかがでしょう。URLが不要なモバイル用のトラッキングIDを取得し、[universal-analytics](https://www.npmjs.com/package/universal-analytics) の `Visitor#event`にNode.js・npm・package自体のバージョン、OSの種類などを送信できるようにすると、有用な情報が得られるかと思います。

**Comment by teppeis** [comment]
あざます。yeomanがやってるやつですね。
https://github.com/yeoman/insight

やってみるかな。

**Comment by teppeis** [comment]
一応 npm のissueにとりあえずコメントしたのでこれは閉じます。あざました。
