### ISSUE TITLE
Scoped packageの実用性について

### ISSUE THREAD

**Issue by lacolaco** [watilde/npm#6]
npmの[scoped package](https://docs.npmjs.com/misc/scope)について。

AngularJSはnpmで`angular`パッケージを配布しているが、AngularJSのプラグイン(数千件)の命名規則は様々で、`angular-xxx`だったり`ng-xxx`だったりバラバラである。
Angular公式のサブパッケージもその中に含まれており、`angular-mocks`や`angular-route`などが配布されているが名前では公式のものかサードパーティのものか判別が困難である。

以上の反省を踏まえてAngularチームではscoped packageを使ってangular orgでのパッケージ管理を行うべきではないかと議論されている。現に先日`@angular/router`という新しいパッケージが公開された。
ただまだこの方針は決定ではなく手探り状態である。具体的な議論の内容としては

```
Researching scoped packages to see if this is the right path
Pro: We own a namespace that nobody can name-squat on our package names
Con: The '@' symbol looks strange in imports and may not work for some
```

ということで、一見便利なようだが、OSやファイルシステムの違いによって問題が起きないのか、ユーザーが見慣れない`@`記号で戸惑うことはないかということを危惧している。
この不安について、もしnpmとしての見解があれば聞かせて欲しい。

**Comment by watilde** [comment]
とても良いユースケースだと思いますよ！個人的には大賛成です :smiley: 
動作に関しても、Angularの場合はNode.jsのバージョンが `>= 5.4.1 < 6` であること想定しているようなので、特に問題なく動きます。 https://github.com/angular/angular/blob/master/package.json#L21-L23

まだ浸透してるとは言いがたいので、READMEに丁寧に書くようにするとissue報告が減りそうですね

```
## Install scoped package
$ npm install --save @angular/router
```

Node.jsのLTSの中で一番古いv0.10.xだとnpm@1.xが使われていますが、こちらもまだLTSとして更新されているので使用不可ってことにはならないかなぁと思います。 https://github.com/npm/npm/tree/1.4.x

---

追記、npm@1.4.xは開発が既に止まっているようでした。Node.js v0.10.x, v0.12.x へは npm@2系の最新が入るそうです。https://github.com/nodejs/node/pulls?utf8=%E2%9C%93&q=is%3Apr+is%3Aopen+%22upgrade+npm+in+LTS+to+2.14.21%22

**Comment by lacolaco** [comment]
まだ普及してないだけで慣れの問題っぽいですね…
ただバージョン指定の同じ記号なのはどうなんだろうな〜と思います

`npm i @angular/router@1.0.0`ではなくて`npm i angular/router@1.0.0
`と書けるほうが良い気がするんですが、なぜ`@`をつけるようになったんですか？
2016/03/17 1:36 "Daijiro Wachi" notifications@github.com:

**Comment by watilde** [comment]
理由としては消去法になっていて、
1. `user/repo`とすると、scoped packageより前にサポートされていたGitHubの短縮表記とぶつかってしまう
2. `npm install ~org/foo` だと、shellがホームディレクトリを指してしまう
3. `npm install $org/foo` だと、`$org`変数を展開してしまう
4. `+`, `#`, `%` も同様に問題を抱えている

ということで `@`の採用が決まったそうです。
調べてみたら面白かったです、良い質問をありがとうございます〜。

参考:
https://github.com/npm/npm/issues/5239

**Comment by lacolaco** [comment]
参考になりました。ありがとうございます！
