### ISSUE TITLE
日本語issue trackerの改善案

### ISSUE THREAD

**Issue by watilde** [watilde/npm#7]
TwitterやGitterの窓口を設けようかなと考えてます。

質問やバグ報告はこのリポジトリで行えると参照がしやすくて助かるのですが、[eslint-jp](https://github.com/eslint/eslint-jp) を見習って気軽に雑談ができるような場所があっても良いかなと考えています。

また、回答例やTips、翻訳などに関して情報発信が出来たら便利になるのか試したいのでTwitterアカウントを取ってみました。合わせて活用したいと思います。[@npmjsjp](https://twitter.com/npmjsjp)

なので、仕組みづくりのToDoとして
- [x] Gitterチャットの開設
- [ ] Twitterアカウントの運用開始

をあげておきます。

他に何か改善案がある方は、お気軽にこちらのissueまでコメント頂けると嬉しいです！

**Comment by tgfjt** [comment]
雑談で思い浮かんだのは Slack でした。

**Comment by watilde** [comment]
Fujitaさんコメントありがとうございます〜。

Slackもちょっと考えたんですが、１つの話題に終始するRepositoryならGitterの方が向いているかなと思っています！そんなGitterの優位点：
- ログインしていなくても会話のログを閲覧できる
- GitHubのアカウントでログインができる

**Comment by geckotang** [comment]
ZenHubとか使うとIssueが増えた時に管理がしやすいかなという気がします。

**Comment by watilde** [comment]
Gitterが機能してるのでTwitterアカウントは一旦フリーズしてみようと思います
