### ISSUE TITLE
npm shrinkwrapが失敗する

### ISSUE THREAD

**Issue by geckotang** [watilde/npm#9]
- 背景
  - 依存モジュールのバージョンを固定したかったため `npm shrinkwrap` を使用した
- 実行環境
  - Node.jsのバージョン
    - v4.4.0
  - npmのバージョン
    - 2.14.20
  - OSのバージョン
    - Mac 10.11.3
- エラーログ
  - https://gist.github.com/geckotang/d276af9e2ff4608d900c7fe81dacd945

**Comment by watilde** [comment]
教えてもらったgulp-utilのversion、依存パッケージの `dateformat` が未サポートなversion rangeになってると思います。`gulp-help`を更新すればおそらく直ると思います！

:koko: https://github.com/gulpjs/gulp-util/blob/7afc6e4d3d807e714e071018183c42892c08711e/package.json#L15

**Comment by geckotang** [comment]
@watilde `gulp-help`を最新のものにしたら動作しました。ありがとうございます。
